spring.application.name=employee-management

server.port=8080

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.show-sql=true

# Enables H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Use file-based H2 database
spring.datasource.url=jdbc:h2:file:./data/employeedb

# Hibernate
spring.jpa.hibernate.ddl-auto=update